### ISSUE TITLE
Make sure all SDKs subscribe to the correct topics

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#568]
Each SDK has a different approach to subscriptions, we need to standardize the subscriptions to these well defined list of topics:
- Consumer properties control path (e.g. `<realm>/<device_id>/control/consumer/properties`)
- Server owned interfaces subpaths (e.g. `<realm>/<device_id>/<interface_name>/#`)

Right now many SDKs subscribe also to this topics, which must be _removed_:
- Device owned interfaces
- Server owned interface root path (e.g. `<realm>/<device_id>/interface_name>`)

The latter was inherited from the first Astarte SDKs, it was there for future usage but it isn't currently used for anything so it can be removed and possibly added again when it's needed.

SDK checklist to close this issue:
- [x]  Qt5: https://github.com/astarte-platform/astarte-device-sdk-qt5/pull/19
- [x] Java
- [x] Elixir: https://github.com/astarte-platform/astarte-device-sdk-elixir/pull/31
- [x] ESP32: https://github.com/astarte-platform/astarte-device-sdk-esp32/pull/66
- [x] Go: https://github.com/astarte-platform/astarte-device-sdk-go/pull/14
- [x] Python: https://github.com/astarte-platform/astarte-device-sdk-python/pull/7

**Comment by rbino** [comment]
Closing this since it's implemented in all SDKs
