### ISSUE TITLE
[meta] Allow multiple Astarte instances to share the same database

### ISSUE THREAD

**Issue by Annopaolo** [astarte-platform/astarte#924]
Since the Astarte Kubernetes Operator allows one to have more than one Astarte instance in the same cluster, a natural generalization is to allow multiple Astarte instances to share the same ScyllaDB/Cassandra database.
We should add a way to avoid naming conflicts between keyspaces (as Astarte realms), e.g. two different instances having the `test` realm (or just having the same `astarte` keyspace :eyes:).
A possible solution is adding an Astarte instance ID with which to compute the keyspace name, together with the realm name.

This is a meta issue to keep track of changes in different repos:
- [ ] here
- [x] in astarte_core (see https://github.com/astarte-platform/astarte_core/pull/105)
- [x] in astarte_vmq_plugin (see https://github.com/astarte-platform/astarte_vmq_plugin/pull/85)
- [x] in astarte_data_access

**Comment by eddbbt** [comment]
this also needs to be added https://github.com/astarte-platform/astarte_flow/pull/161

**Comment by Annopaolo** [comment]
Still open in this repo
